CREATE TABLE USUARIO_PRESTADORA (
  FK_ID_USUARIO NUMBER(9) NOT NULL,
  FK_ID_PRESTADORA NUMBER(9) NOT NULL,
  CONSTRAINT FK_ID_USUARIO_PRESTADORA FOREIGN KEY (FK_ID_USUARIO) REFERENCES USUARIO (PK_ID_USUARIO)
);
INSERT INTO USUARIO_PRESTADORA (FK_ID_USUARIO,FK_ID_PRESTADORA)
SELECT PK_ID_USUARIO, PK_ID_PRESTADORA FROM PRESTADORA_X_USUARIO;

CREATE TABLE USUARIO_GRUPO_PERFIL (
  FK_ID_USUARIO NUMBER(9) NOT NULL,
  FK_ID_GRUPO_PERFIL NUMBER(9) NOT NULL,
  CONSTRAINT FK_ID_USUARIO_GRUPO_PERFIL FOREIGN KEY (FK_ID_USUARIO) REFERENCES USUARIO (PK_ID_USUARIO),
  CONSTRAINT FK_ID_GRUPO_PERFIL_USUARIO FOREIGN KEY (FK_ID_GRUPO_PERFIL) REFERENCES GRUPO_PERFIL (PK_ID_GRUPO_PERFIL)
);
INSERT INTO USUARIO_GRUPO_PERFIL (FK_ID_USUARIO,FK_ID_GRUPO_PERFIL)
SELECT PK_ID_USUARIO, PK_ID_GRUPO_PERFIL FROM USUARIO_X_GRUPO_PERFIL;

DROP TABLE PRESTADORA_X_USUARIO;
DROP TABLE USUARIO_X_GRUPO_PERFIL;

alter table GRUPO_PERFIL_X_PERFIL drop column PK_ID_GRUPO_PERFIL_X_PERFIL;

CREATE OR REPLACE SYNONYM "SNOA"."MGU_USUARIO_X_GRUPO_PERFIL" FOR "MGU"."USUARIO_GRUPO_PERFIL";